# Generated by Django 5.1.3 on 2024-11-09 14:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("consulting", "Educational Consulting and Leadership"),
                            (
                                "research",
                                "Research, Data Analysis, and Policy Development",
                            ),
                            ("tech", "Technology and Digital Platform Development"),
                            ("stem", "STEM Education and International Collaboration"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio_images/")),
                ("client", models.CharField(blank=True, max_length=100, null=True)),
                ("project_date", models.DateField(blank=True, null=True)),
                ("project_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="BlogPost",
        ),
        migrations.RemoveField(
            model_name="project",
            name="technologies",
        ),
        migrations.DeleteModel(
            name="Publication",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Technology",
        ),
    ]
