# Generated by Django 5.1.3 on 2024-11-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_blogpost_category_contact_pdffile_post_resume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(upload_to="portfolio_images/%Y/%m/%d/"),
        ),
    ]
